### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dbmtrde** [Quoorex/minecraft-server-eu-bot#11]
Voting for the url https://minecraft-server.eu/vote/index/##########

main.py:54: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
  profile = webdriver.FirefoxProfile()
main.py:87: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Firefox(profile, options=options, executable_path=driver_path)
main.py:87: DeprecationWarning: firefox_profile has been deprecated, please pass in an Options object
  driver = webdriver.Firefox(profile, options=options, executable_path=driver_path)
Traceback (most recent call last):
  File "main.py", line 87, in init_driver
    driver = webdriver.Firefox(profile, options=options, executable_path=driver_path)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/firefox/webdriver.py", line 179, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 268, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 359, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 198, in <module>
    bot.run(usernames, vote_urls)
  File "main.py", line 180, in run
    driver = self.init_driver()
  File "main.py", line 90, in init_driver
    self.install_driver()
  File "main.py", line 38, in install_driver
    gdd.download_and_install()
  File "/home/dbm/.local/lib/python3.8/site-packages/webdrivermanager/base.py", line 271, in download_and_install
    filename_with_path = self.download(version, show_progress_bar=show_progress_bar)
  File "/home/dbm/.local/lib/python3.8/site-packages/webdrivermanager/base.py", line 227, in download
    (download_url, filename) = self.get_download_url(version)
  File "/home/dbm/.local/lib/python3.8/site-packages/webdrivermanager/gecko.py", line 42, in get_download_url
    version = self._parse_version(version)
  File "/home/dbm/.local/lib/python3.8/site-packages/webdrivermanager/base.py", line 155, in _parse_version
    return self.get_latest_version()
  File "/home/dbm/.local/lib/python3.8/site-packages/webdrivermanager/gecko.py", line 59, in get_latest_version
    return self._get_latest_version_with_github_page_fallback(self.gecko_driver_releases_url, self.fallback_url, "latest")
  File "/home/dbm/.local/lib/python3.8/site-packages/webdrivermanager/base.py", line 168, in _get_latest_version_with_github_page_fallback
    latest_release = tree.find("div", {"class", "release-header"}).findAll("a")[0]
AttributeError: 'NoneType' object has no attribute 'findAll'

**Comment by Quoorex** [comment]
This project has not been maintained for a very long time. It may be completely broken by now.
